package com.example.domain

import android.content.Context
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object ProjectCodeExporter {

    data class ExportedProjectSource(
        val projectName: String,
        val packageName: String,
        val buildGradleKts: String,
        val androidManifestXml: String,
        val mainActivityKt: String,
        val proguardRulesPro: String,
        val settingsGradleKts: String
    )

    fun createProjectZipFile(context: Context, project: ApkProject): Pair<File, Uri> {
        val source = generateCompleteProjectSource(project)
        val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val safeName = project.name.replace(Regex("[^a-zA-Z0-9_]"), "_").lowercase()
        val zipFile = File(exportDir, "${safeName}_v${project.versionName}_project.zip")

        ZipOutputStream(FileOutputStream(zipFile)).use { zos ->
            fun addZipEntry(path: String, content: String) {
                val entry = ZipEntry(path)
                zos.putNextEntry(entry)
                zos.write(content.toByteArray(Charsets.UTF_8))
                zos.closeEntry()
            }

            addZipEntry("app/build.gradle.kts", source.buildGradleKts)
            addZipEntry("app/src/main/AndroidManifest.xml", source.androidManifestXml)
            val packagePath = source.packageName.replace('.', '/')
            addZipEntry("app/src/main/java/$packagePath/MainActivity.kt", source.mainActivityKt)
            addZipEntry("app/proguard-rules.pro", source.proguardRulesPro)
            addZipEntry("settings.gradle.kts", source.settingsGradleKts)
            addZipEntry("gradle.properties", "android.useAndroidX=true\nandroid.nonTransitiveRClass=true\norg.gradle.jvmargs=-Xmx2048m\n")
            addZipEntry("README.md", "# ${project.name}\n\nGenerated by Devator Studio.\n\nPackage: `${project.packageName}`\nTarget SDK: `${project.targetSdk}`\nVersion: `${project.versionName}`\n")
        }

        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            zipFile
        )
        return Pair(zipFile, uri)
    }

    fun generateCompleteProjectSource(project: ApkProject): ExportedProjectSource {
        val buildGradle = """
            // Real Gradle Build Script Generated by Devator Studio
            plugins {
                alias(libs.plugins.android.application)
                alias(libs.plugins.kotlin.compose)
                alias(libs.plugins.google.devtools.ksp)
            }

            android {
                namespace = "${project.packageName}"
                compileSdk = ${project.targetSdk}

                defaultConfig {
                    applicationId = "${project.packageName}"
                    minSdk = 24
                    targetSdk = ${project.targetSdk}
                    versionCode = ${project.versionCode}
                    versionName = "${project.versionName}"

                    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
                }

                buildTypes {
                    release {
                        isMinifyEnabled = ${project.isProGuardActive}
                        isShrinkResources = ${project.isR8ShrinkingEnabled}
                        proguardFiles(
                            getDefaultProguardFile("proguard-android-optimize.txt"),
                            "proguard-rules.pro"
                        )
                    }
                    debug {
                        applicationIdSuffix = ".debug"
                        isDebuggable = true
                    }
                }
                
                compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_11
                    targetCompatibility = JavaVersion.VERSION_11
                }
                
                buildFeatures {
                    compose = true
                }
            }

            dependencies {
                implementation(platform(libs.androidx.compose.bom))
                implementation(libs.androidx.activity.compose)
                implementation(libs.androidx.compose.material3)
                implementation(libs.androidx.compose.ui)
                implementation(libs.androidx.compose.ui.graphics)
                implementation(libs.androidx.lifecycle.runtime.ktx)
                implementation(libs.androidx.lifecycle.viewmodel.compose)
                implementation(libs.androidx.room.ktx)
                implementation(libs.androidx.room.runtime)
                ksp(libs.androidx.room.compiler)
            }
        """.trimIndent()

        val manifest = """
            <?xml version="1.0" encoding="utf-8"?>
            <manifest xmlns:android="http://schemas.android.com/apk/res/android">

                <uses-permission android:name="android.permission.INTERNET" />
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
                <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
                <uses-permission android:name="android.permission.VIBRATE" />

                <application
                    android:allowBackup="true"
                    android:icon="@mipmap/ic_launcher"
                    android:label="${project.name}"
                    android:roundIcon="@mipmap/ic_launcher_round"
                    android:supportsRtl="true"
                    android:theme="@android:style/Theme.Material.NoActionBar">
                    
                    <activity
                        android:name=".MainActivity"
                        android:exported="true">
                        <intent-filter>
                            <action android:name="android.intent.action.MAIN" />
                            <category android:name="android.intent.category.LAUNCHER" />
                        </intent-filter>
                    </activity>
                </application>

            </manifest>
        """.trimIndent()

        val mainActivity = """
            package ${project.packageName}

            import android.os.Bundle
            import androidx.activity.ComponentActivity
            import androidx.activity.compose.setContent
            import androidx.activity.enableEdgeToEdge
            import androidx.compose.foundation.layout.*
            import androidx.compose.material3.*
            import androidx.compose.runtime.*
            import androidx.compose.ui.Alignment
            import androidx.compose.ui.Modifier
            import androidx.compose.ui.unit.dp

            class MainActivity : ComponentActivity() {
                override fun onCreate(savedInstanceState: Bundle?) {
                    super.onCreate(savedInstanceState)
                    enableEdgeToEdge()
                    setContent {
                        MaterialTheme {
                            Surface(modifier = Modifier.fillMaxSize()) {
                                Scaffold { innerPadding ->
                                    Column(
                                        modifier = Modifier
                                            .fillMaxSize()
                                            .padding(innerPadding)
                                            .padding(24.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally,
                                        verticalArrangement = Arrangement.Center
                                    ) {
                                        Text(
                                            text = "${project.name}",
                                            style = MaterialTheme.typography.headlineMedium
                                        )
                                        Spacer(modifier = Modifier.height(8.dp))
                                        Text(
                                            text = "Version: v${project.versionName} (Build ${project.versionCode})",
                                            style = MaterialTheme.typography.bodyMedium
                                        )
                                        Spacer(modifier = Modifier.height(16.dp))
                                        Button(onClick = { /* Action */ }) {
                                            Text("Launch Tool")
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        """.trimIndent()

        val proguard = """
            # ProGuard / R8 Rules generated for ${project.name}
            -keepclassmembers class * {
                @androidx.room.Dao *;
                @androidx.room.Entity *;
            }
            -dontwarn okhttp3.**
            -dontwarn kotlinx.coroutines.**
        """.trimIndent()

        val settingsGradle = """
            pluginManagement {
                repositories {
                    google()
                    mavenCentral()
                    gradlePluginPortal()
                }
            }
            dependencyResolutionManagement {
                repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
                repositories {
                    google()
                    mavenCentral()
                }
            }
            rootProject.name = "${project.name.replace(" ", "")}"
            include(":app")
        """.trimIndent()

        return ExportedProjectSource(
            projectName = project.name,
            packageName = project.packageName,
            buildGradleKts = buildGradle,
            androidManifestXml = manifest,
            mainActivityKt = mainActivity,
            proguardRulesPro = proguard,
            settingsGradleKts = settingsGradle
        )
    }
}
